### ISSUE TITLE
What is the date format?

### ISSUE THREAD

**Issue by hereismari** [mgulcin/DL_Rec#1]
Hello,

Thank you for making this implementation available!

I have some doubts and would be very helpful to have more details.

* What is the input format for the train and to generate recommendations?
* Why haven't you use doc2vec instead of word2vec since your goal is to have vectors for the users and items?

Thank you !

**Comment by mgulcin** [comment]
Hello,
What I tried to implement was to apply Paragraph2Vec method in recommendation. At the time of my implementation, "gensim" framework didn't have the related module, so I tried to implement it myself using their Word2Vec implementation. (As far as I know, they now have the Paragraph2Vec (Doc2Vec) module in their framework).

In Paragraph2Vec method they were using the paragraph ids and words, e.g. "paragraph_i word_1 word2 ...". Inspiring from that I created the input as "user1 item1 item2 ...". I included the information for each user on each row; e.g. row1--> "user1 item1 item2 ...", row2-->"user2 item21 item22 ..."

Thank you for your time and interest :)

**Comment by hereismari** [comment]
Hello @mgulcin,

Thank you for the quick answer!

> What I tried to implement was to apply Paragraph2Vec method in recommendation. At the time of my implementation, "gensim" framework didn't have the related module, so I tried to implement it myself using their Word2Vec implementation. (As far as I know, they now have the Paragraph2Vec (Doc2Vec) module in their framework).

I see, I had no idea the doc2vec did not exist at the time.

> Thank you for your time and interest :)

Thank you! Best wishes!
